// // export const topics = [
// //   'DeFi innovations',
// //   'meme token hype',
// //   'gas fees frustration',
// //   'NFT trends',
// //   'market predictions',
// //   'crypto regulations',
// // ];

// export const slangTerms = [
//   'Ape in',
//   'Bagholder',
//   'Bear market',
//   'Bull run',
//   'BTFD (Buy The Fucking Dip)',
//   'Copium',
//   'Crypto winter',
//   'DCA (Dollar Cost Averaging)',
//   'Degen',
//   'Diamond hands',
//   'Dipping',
//   'Do only research (DOR)',
//   'DYOR (Do Your Own Research)',
//   'Flippening',
//   'FOMO (Fear Of Missing Out)',
//   'FUD (Fear, Uncertainty, Doubt)',
//   'GM (Good Morning)',
//   'GMI (Gonna Make It)',
//   'HODL (Hold On for Dear Life)',
//   'Hopium',
//   'Jeet',
//   'Lambo',
//   'LFG ',
//   'Losing your shirt',
//   'Market cap',
//   'Maxi (Maximalist)',
//   'Moon',
//   'Moonshot',
//   'NGMI (Not Going to Make It)',
//   'Paper hands',
//   'Panic sell',
//   'Pump and dump',
//   'Rekt',
//   'Rug pull',
//   'SAFU (Safe As Fuck)',
//   'Satoshi',
//   'Ser',
//   'Shill',
//   'Shitcoin',
//   'Sweeping the floor',
//   'To the moon',
//   'Vaporware',
//   'WAGMI (We Are All Gonna Make It)',
//   'Wen moon',
//   'Whale',
//   'Yield farming',
//   'YOLO (You Only Live Once)',
//   'Zap',
//   'Airdrop',
//   'Ape out',
//   'Bidding war',
//   'Coin burning',
//   'Degen trader',
//   'Floor price',
//   'Gas',
//   'Gas war',
//   'Giga chad',
//   'Grind',
//   'Halving',
//   'Honey pot',
//   'ICO (Initial Coin Offering)',
//   'IDO (Initial DEX Offering)',
//   'Kek',
//   'Liquidity pool',
//   'MEV (Miner Extractable Value)',
//   'Mooning',
//   'NFA (Not Financial Advice)',
//   'Normie',
//   'OG (Original Gangster)',
//   'PA (Price Action)',
//   'PFP (Profile Picture)',
//   'Ponzi',
//   'Pumping',
//   'Ratio',
//   'REKT store',
//   'Rekt whale',
//   'Slippage',
//   'Snipe',
//   'Staking',
//   'Stonks',
//   'TLDR (Too Long; Didn’t Read)',
//   'Tokenomics',
//   'Volume',
//   'Wallet drainer',
//   'Wick',
//   'Wick dipper',
//   'Wick snipe',
//   'WTF (Wag The Dog)',
//   'Zk-rollup',
//   'Aping into a presale',
//   'Backdooring',
//   'Bearish divergence',
//   'Bullish divergence',
//   'Candlestick',
//   'CEX (Centralized Exchange)',
//   'DEX (Decentralized Exchange)',
//   'Dump',
//   'EIP (Ethereum Improvement Proposal)',
//   'Flippen',
//   'Fork',
//   'Front running',
//   'Gas token',
//   'Gwei',
//   'Hashing',
//   'Hyperbull',
//   'Incentivized testnet',
//   'JOMO (Joy Of Missing Out)',
//   'KYC (Know Your Customer)',
//   'Layer 2',
//   'Liquidity',
//   'Minting',
//   'Moonbag',
//   'Nocoiner',
//   'P&D (Pump and Dump)',
//   'Paper gain',
//   'Rekt capital',
//   'Rekt by the market',
//   'Satoshi era',
//   'Scamcoin',
//   'Shilling',
//   'Shill thread',
//   'Slippage tolerance',
//   'Sniping bot',
//   'Stablecoin',
//   'Sweat',
//   'Tendies',
//   'Token distribution',
//   'Vesting',
//   'Whitelist',
//   'Wick liquidity',
//   'Wick manipulation',
//   'Wick resistance',
//   'Zero confirmation',
//   'Ath (All-Time High)',
//   'Atl (All-Time Low)',
//   'Bear trap',
//   'Bull trap',
//   'Candlestick pattern',
//   'Censorship resistance',
//   'Consensus mechanism',
//   'Cross-chain',
//   'Degen box',
//   'Eth killer',
//   'Fiat',
//   'Flash loan',
//   'Front run',
//   'Gasless',
//   'Gwei spike',
//   'Hot wallet',
//   'Iceberg order',
//   'Jitter',
//   'Kekistan',
//   'Layer 1',
//   'Liquidity mining',
//   'Master node',
//   'Meme coin',
//   'Moon farming',
//   'Node',
//   'On-chain',
//   'Panic buying',
//   'Panic moon',
//   'Pump group',
//   'Rekt by slippage',
//   'Rekt trade',
//   'Satoshi flip',
//   'Scammer',
//   'Shill army',
//   'Slippage protection',
//   'Snipe bot',
//   'Stop loss',
//   'Token burn',
//   'Vapor',
//   'Wash trading',
//   'Wick candle',
//   'Wick pump',
//   'Yield',
//   'Zap in',
//   'Zap out',
// ];

// export const topics = [
//   'The next big rug pull',
//   'Meme tokens with the most potential',
//   'How to spot a scam coin',
//   'Best times to ape into a presale',
//   `Crypto Twitter's latest shilling`,
//   'NFTs that are just JPEGs',
//   'Gas fee spikes during token launches',
//   'The art of FOMO trading',
//   'Why I lost my shirt on a shitcoin',
//   'Yield farming gone wrong',
//   'Celebrity endorsements gone bad',
//   'Pump and dump group chats',
//   'The psychology behind HODLing',
//   'Leverage trading horror stories',
//   'Crypto influencers who are full of shit',
//   'When to sell before the dip',
//   'Crypto market cycles - are we in a bull run?',
//   'The best degen trading strategies',
//   'NFTs with the most utility... or not',
//   'Altcoins that might actually go to the moon',
//   `The myth of 'buy the dip'`,
//   'Which blockchain has the worst gas fees?',
//   'Crypto tax evasion myths',
//   'The allure of low-cap gems',
//   'Meme coin marketing tactics',
//   'How to recover from being rekt',
//   'The risks of leverage in DeFi',
//   'The next altseason - when and why',
//   'NFTs that nobody wants',
//   'The dangers of market manipulation',
//   'Predicting the next crypto crackdown',
//   'Airdrop farming: worth the time?',
//   'The impact of Twitter on crypto prices',
//   'DeFi protocols that drain your wallet',
//   'The psychology of panic selling',
//   'How to spot a Ponzi scheme',
//   'Crypto gambling dApps to avoid',
//   'Yield farming scams',
//   'The ethics of insider trading in crypto',
//   'When influencers shill their own coins',
//   'Crypto market cap manipulation',
//   `The worst crypto advice you've ever heard`,
//   'Decentralized exchanges that suck',
//   'Why I love trading shitcoins',
//   'The rise and fall of stablecoins',
//   'NFT royalties - fair or exploitative?',
//   'The truth about "safu" projects',
//   'Crypto scams that were almost believable',
//   'The best times to buy the fear',
//   'Why most crypto predictions are bullshit',
//   'The allure of high-risk, high-reward trades',
//   'Flash loans: the good, the bad, and the ugly',
//   'Crypto community wars',
//   'The future of meme coins',
//   'How to deal with a bear market',
//   'The most overhyped tokens of the year',
//   'NFT flippers: heroes or villains?',
//   'Crypto liquidity pools - worth it or nah?',
//   'The impact of gas wars on trading',
//   'Crypto Twitter wars and their effects',
//   'The appeal of shitcoin gambling',
//   'When to trust a crypto project roadmap',
//   'The myth of the Ethereum killer',
//   'Crypto influencers who got rekt',
//   'The art of reading between the lines in crypto whitepapers',
//   'Predicting token burns and their impacts',
//   'The most ridiculous crypto memes',
//   'The psychology behind crypto addiction',
//   'Crypto social media manipulation techniques',
//   'How to survive a crypto winter',
//   'The best shitcoin names',
//   'Why some NFTs are just digital trash',
//   'The truth about token presales',
//   'Crypto whales - to follow or to fear?',
//   'The impact of celebrity tweets on crypto',
//   'The dark side of crypto staking',
//   'The rise of gaming tokens',
//   'Crypto market cycles and how to play them',
//   'The allure of rug pull stories',
//   'DeFi yield aggregators - a blessing or a curse?',
//   'The most dramatic crypto market crashes',
//   'The potential of layer 2 solutions',
//   'Crypto and the environment - green or greed?',
//   'The ethics of selling before the pump',
//   'Crypto lending platforms that went under',
//   'The psychology of FUD spreading',
//   'How to spot a crypto pyramid scheme',
//   'The future of decentralized finance',
//   'The impact of regulatory news on crypto',
//   'Meme coin community governance',
//   `The reality of 'to the moon' predictions`,
//   'The psychology of diamond hands',
//   'Crypto scams that could have been avoided',
//   'The allure of crypto Twitter',
//   'Crypto liquidity - the myth and the reality',
//   'The best ways to cope with a crypto loss',
//   'The truth about crypto influencers',
//   'How to deal with crypto FUD',
//   'Crypto projects that rekt their investors',
//   'The psychology of market pumps',
//   'Crypto trading bots - friend or foe?',
//   'The most controversial crypto projects',
//   'The impact of gas fees on small traders',
//   'The ethics of market manipulation',
//   'The rise of crypto gambling',
//   `Crypto Twitter's role in price discovery`,
//   'The dangers of aping into anything',
//   'The allure of crypto presales',
//   'Crypto token burns - effective or just hype?',
//   'The psychology behind the crypto hype cycle',
//   'The best shitcoin stories',
//   'Crypto market corrections - what to do?',
//   'The impact of social media on crypto trends',
//   'The risks of high leverage trading',
//   'Crypto influencers who turned out to be scammers',
//   'The allure of crypto airdrops',
//   `The reality of crypto 'insurance'`,
//   'Crypto market cap vs. actual utility',
//   'The psychology of being a bagholder',
//   'Crypto scams that started with promise',
//   'The ethics of front running in DeFi',
//   'The future of meme tokens',
//   'Crypto trading during geopolitical events',
//   'The impact of FOMO on trading decisions',
//   'The allure of crypto yield farming',
//   'Crypto Twitter drama - the latest',
//   'The psychology of crypto addiction',
//   'Crypto projects that promised too much',
//   'The ethics of shilling your own coins',
//   'The impact of crypto on traditional finance',
//   'Crypto market sentiment tools - helpful or harmful?',
//   'The allure of crypto gambling sites',
//   'Crypto scams that used celebrity endorsements',
//   'The psychology of crypto trading',
//   `Crypto Twitter's influence on market trends`,
//   `The allure of shitcoin speculation`,
//   'Crypto market cycles - are they predictable?',
//   'The ethics of trading with insider info',
//   'Crypto projects with the most hype',
//   'The psychology of trading during a dip',
//   'The impact of gas fee wars on DeFi',
//   'Crypto scams that prey on FOMO',
//   'The allure of crypto liquidity pools',
//   `Crypto Twitter's role in project success`,
//   `The ethics of market making in crypto`,
//   'Crypto market sentiment and how to read it',
//   'The allure of staking in DeFi',
//   'Crypto scams that were almost undetectable',
//   'The psychology of crypto community behavior',
//   'Crypto projects that fell from grace',
//   'The impact of regulatory changes on trading',
//   'Crypto market cap - true value or just numbers?',
//   'The allure of crypto yield aggregators',
//   'Crypto scams that exploited trust',
//   'The psychology of crypto FUD',
//   `Crypto Twitter's effect on token prices`,
//   `The ethics of crypto trading bots`,
//   'Crypto market corrections - survival strategies',
//   'The allure of crypto gambling dApps',
//   'Crypto projects with the most potential',
//   'The psychology of market pumps and dumps',
//   'Crypto scams that looked legit',
//   'The impact of social media on crypto volatility',
//   'The allure of high-risk trades',
//   'Crypto market cycles - learning from history',
//   'The ethics of crypto influencers',
//   'Crypto liquidity - myths vs. realities',
//   'The psychology of holding through a crash',
//   'Crypto projects that rekt their community',
//   'The impact of gas fees on DeFi adoption',
//   'Crypto scams that started with a dream',
//   'The allure of crypto airdrops',
//   'Crypto market sentiment - how to gauge it?',
//   'The psychology of crypto trading losses',
//   'Crypto projects with the most controversial roadmaps',
//   'The impact of regulatory news on crypto prices',
//   'The allure of crypto staking rewards',
//   'Crypto scams that fooled even experts',
//   'The psychology of crypto market manipulation',
//   `Crypto Twitter's influence on project launches`,
//   `The ethics of trading on rumors`,
//   'Crypto market cap - what does it really mean?',
//   'The allure of crypto liquidity mining',
//   'Crypto scams that used celebrity names',
//   'The psychology of crypto FOMO',
//   'Crypto projects that promised the moon',
//   'The impact of social media on crypto scams',
//   'The allure of high-leverage trading',
//   'Crypto market cycles - are we due for a change?',
//   'The ethics of shilling on crypto forums',
//   'Crypto liquidity pools - to join or not?',
//   'The psychology of crypto trading addiction',
//   'Crypto projects that went from zero to hero',
//   'The impact of gas fees on small investors',
//   'Crypto scams that preyed on greed',
//   'The allure of crypto presales',
//   'Crypto market sentiment - tools and traps',
//   'The psychology of trading during market fear',
//   'Crypto influencers who became memes',
//   'The impact of regulatory actions on crypto',
//   'The allure of crypto yield farming strategies',
//   'Crypto scams that were too good to be true',
//   'The psychology of market panic',
//   `Crypto Twitter's role in spreading FUD`,
//   `The ethics of crypto trading advice`,
//   `Crypto market corrections - what's next?`,
//   `The allure of crypto gambling platforms`,
//   'Crypto projects with the biggest promises',
//   'The psychology of crypto community loyalty',
//   'Crypto scams that exploited new tech',
//   'The impact of social media on crypto market sentiment',
//   'The allure of high-risk, high-reward crypto',
//   'Crypto market cycles - learning or luck?',
//   'The ethics of using insider info',
//   `Crypto liquidity - where's the real value?`,
//   `The psychology of holding through a bull run`,
//   'Crypto projects that turned their community into believers',
//   'The impact of gas fees on DeFi usability',
//   'Crypto scams that started with innovation',
//   'The allure of crypto airdrops and farming',
//   'Crypto market sentiment - navigating the noise',
//   'The psychology of crypto trading psychology',
//   'Crypto projects with the most controversial decisions',
//   'The impact of regulatory changes on crypto adoption',
//   'The allure of crypto staking and its risks',
//   'Crypto scams that fooled the masses',
//   'The psychology of crypto market hype',
//   `Crypto Twitter's influence on project failures`,
//   'The ethics of trading on market rumors',
//   'Crypto market cap - perception vs. reality',
//   'The allure of crypto liquidity mining rewards',
//   'Crypto scams that played with trust',
//   'The psychology of crypto FOMO trading',
//   'Crypto projects that promised more than they could deliver',
//   'The impact of social media on crypto project launches',
//   'The allure of high-leverage trading in crypto',
//   'Crypto market cycles - timing the market',
//   'The ethics of crypto advice from influencers',
//   'Crypto liquidity pools - are they worth the risk?',
//   'The psychology of crypto trading losses and recovery',
//   'Crypto projects that went from obscurity to fame',
//   'The impact of gas fees on everyday trading',
//   'Crypto scams that exploited community trust',
//   'The allure of crypto presales and their pitfalls',
//   'Crypto market sentiment - reading between the tweets',
//   'The psychology of trading through market fear',
//   'Crypto influencers who became part of the lore',
//   'The impact of regulatory crackdowns on crypto',
//   'The allure of crypto yield farming - the new gold rush?',
// ];

export const degenerateTopics = [
  'Mooning shitcoins under $0.01',
  'Rug pulls that left wallets bleeding',
  'Pump and dump schemes on Doge derivatives',
  'NFT scams that made the news',
  'Meme coin with no utility hitting ATH',
  'Trading on leverage with 100x margin',
  'ICOs that vanished into thin air',
  'Shilling garbage tokens in DMs',
  'FOMO into every new dip',
  "Buying the top thinking it's the bottom",
  "Selling the bottom thinking it's the top",
  'Aping into presales with no audit',
  'Getting rekt by flash loans',
  'Shitcoin with a dog logo on the moon',
  'Yield farming on a sketchy DEX',
  'Staking in pools that rug overnight',
  'Betting on crypto celeb endorsements',
  'Holding a bag of dead BSC tokens',
  'Trading based on Twitter memes',
  'Losing sleep over candle wicks',
  'Spamming Telegram groups for referrals',
  'NFTs of literal trash selling for ETH',
  'Day trading with no strategy, just vibes',
  'Chasing airdrops like a junkie',
  'Getting phished because you clicked that link',
  'Investing in tokens named after diseases',
  'Falling for Ponzi schemes disguised as DeFi',
  'Getting into crypto because of a Netflix show',
  "Trading with borrowed money from the wife's purse",
  'Shilling your own shitcoin to your grandma',
  'Swapping tokens on a DEX with 0 liquidity',
  'Joining a cult-like crypto community',
  'Buying tokens because of the cute mascot',
  'Losing your seed phrase in a house fire',
  'Investing in a coin because of its Twitter follower count',
  'Creating tokens on a blockchain nobody uses',
  'Getting scammed by a fake Elon Musk tweet',
  'Betting on crypto based on astrological signs',
  'Panic selling during a minor dip',
  "Buying into every ICO with 'AI' in the name",
  'Trading based on random number generators',
  'Getting into crypto to launder money',
  'Using your life savings for crypto gambling',
  "Falling for the 'send ETH to double it' scam",
  'Investing in tokens with no whitepaper',
  'Trading based on dreams or gut feelings',
  "Getting rekt by a fork you didn't understand",
  'Launching a token on a chain with no future',
  'FUD spreading just to manipulate the market',
  'HODLing through a bear market for years',
  'Buying NFTs of celebrity tweets',
  "Trading based on the vibe of the coin's name",
  "Losing money on tokens you can't even pronounce",
  "Investing in a coin because it's 'green'",
  'Getting into crypto to pay for illegal stuff',
  'Accidentally sending ETH to the wrong address',
  'Betting on crypto because your friend made bank',
  'Using your rent money to buy into a presale',
  'Trading while high, making high-risk moves',
  'Buying into every new blockchain launch',
  "Falling for the 'send to get' scam",
  "Investing in tokens only because they're trending",
  'Losing your private key in a digital mess',
  'Joining an MLM disguised as a crypto project',
  'Buying coins with no actual team or roadmap',
  "Trading crypto because you're bored at work",
  'Investing in tokens based on celebrity tweets',
  'Getting into crypto to avoid taxes',
  'Betting on crypto during a global economic crash',
  'Buying tokens with the promise of free lambos',
  'Using all your crypto gains to buy more crypto',
  'Investing in a coin because of its logo color',
  'Getting scammed by a fake crypto exchange',
  'Shilling tokens on dating apps',
  'Trading crypto to impress your crush',
  "Buying into every new 'DeFi' token",
  "Falling for the 'whitelist' scam",
  'Investing in a token because it rhymes with Bitcoin',
  'Losing your crypto in a hack because of a weak password',
  'Buying tokens that promise to solve climate change',
  'Getting into crypto to fund your gambling addiction',
  'Betting on coins with zero social media presence',
  'Trading crypto during a power outage with a hotspot',
  'Investing in tokens because of their catchy slogan',
  "Falling for the 'exclusive club' crypto scam",
  'Buying into tokens with no real use case',
  'Trading crypto while drunk at 3 AM',
  'Investing in a coin because of its Twitter handle',
  'Getting rekt by a sudden delisting',
  'Shilling tokens in public places for exposure',
  'Betting on crypto because of a dream you had',
  "Buying into every new 'privacy' coin",
  'Losing your crypto because you forgot your password',
  'Investing in tokens that promise to mine asteroids',
  'Getting into crypto to fund your conspiracy theories',
  'Trading based on the advice of a fortune teller',
  "Buying tokens because they're 'blessed by the gods'",
  "Falling for the 'limited edition' crypto scam",
  "Investing in a coin because of its mascot's backstory",
  'Betting on crypto because of a viral TikTok video',
  'Falling for a crypto pyramid scheme',
  'Investing in coins with cult followings',
  'Getting into crypto because you saw it on a billboard',
  'Trading based on the number of likes on a tweet',
  "Buying tokens because they're 'community-driven'",
  'Investing in a coin because of its catchy jingle',
  "Falling for the 'secret project' hype",
  'Getting scammed by fake crypto influencers',
  "Betting on crypto because it's 'the future of money'",
  'Buying tokens with the promise of moon trips',
  "Using all your savings for a 'once-in-a-lifetime' opportunity",
  "Investing in a coin because it's trending on Reddit",
  'Getting into crypto to dodge child support',
  "Trading based on the 'vibe' of the market",
  "Falling for 'exclusive' crypto presale events",
  "Investing in tokens because of their 'revolutionary tech'",
  'Getting scammed in crypto gambling sites',
  "Buying into every new 'green' blockchain",
  'Trading crypto because you lost your job',
  "Investing in a coin because of its mascot's meme status",
  "Falling for the 'get rich quick' crypto ads",
  "Getting into crypto to fund your 'off-grid' lifestyle",
  "Betting on crypto because of 'insider' tips",
  "Buying tokens because they're 'the next Bitcoin'",
  'Using your student loan for crypto trading',
  "Investing in tokens with 'infinite' potential",
  'Getting rekt by a sudden market dump',
  'Trading crypto to pay off your gambling debts',
  "Falling for the 'crypto for dummies' scam",
  "Buying into every new 'metaverse' token",
  'Investing in a coin because of its launch party',
  'Getting into crypto to buy fake followers',
  "Betting on crypto because of a psychic's prediction",
  "Buying tokens because they're 'environmentally friendly'",
  "Using your inheritance for a 'sure thing' crypto deal",
  "Investing in tokens with 'life-changing' potential",
  'Getting rekt by a flash crash',
  "Trading crypto because you're 'in the know'",
  "Falling for the 'crypto is the new gold' narrative",
  "Buying into every new 'healthcare' blockchain",
  'Investing in a coin because of its celebrity partnerships',
  "Getting into crypto to fund your 'startup'",
  "Betting on crypto because of a friend's success story",
  "Buying tokens because they're 'the future of art'",
  'Using your tax return for crypto speculation',
  "Investing in tokens with 'world-changing' technology",
  'Getting rekt by a black swan event',
  "Trading crypto to prove you're not 'normie'",
  "Falling for the 'crypto will end poverty' scam",
  "Buying into every new 'social impact' token",
  "Investing in a coin because of its 'cool' name",
  "Getting into crypto to buy 'exclusive' digital goods",
  "Betting on crypto because of 'expert' analysis",
  "Buying tokens because they're 'the new oil'",
  'Using your emergency fund for crypto gambling',
  "Investing in tokens with 'revolutionary' governance",
  'Getting rekt by regulatory crackdowns',
  "Trading crypto because you 'believe in the tech'",
  "Falling for the 'crypto will save the planet' narrative",
  "Buying into every new 'charity' blockchain",
  "Investing in a coin because of its 'revolutionary' team",
  'Getting into crypto to escape financial responsibility',
  "Betting on crypto because of 'insider' leaks",
  "Buying tokens because they're 'the future of entertainment'",
  'Using your credit card for crypto investments',
  "Investing in tokens with 'groundbreaking' privacy features",
  'Getting rekt by exchange hacks',
  "Trading crypto because you 'feel' it's going up",
  "Falling for the 'crypto will replace banks' scam",
  "Buying into every new 'space' related token",
  "Investing in a coin because of its 'legendary' roadmap",
  "Getting into crypto to fund your 'revolution'",
  "Betting on crypto because of 'guru' endorsements",
  "Buying tokens because they're 'the future of identity'",
  'Using your last paycheck for crypto trading',
  "Investing in tokens with 'disruptive' potential",
  'Getting rekt by a sudden market manipulation',
  "Trading crypto because you 'understand' the market",
  "Falling for the 'crypto will democratize finance' narrative",
  "Buying into every new 'music' blockchain",
  "Investing in a coin because of its 'unique' consensus mechanism",
  'Getting into crypto to escape real-world problems',
  "Betting on crypto because of 'expert' predictions",
  "Buying tokens because they're 'the future of gaming'",
  'Using your retirement fund for crypto speculation',
  "Investing in tokens with 'transformative' applications",
  'Getting rekt by a sudden fork',
  "Trading crypto because you 'know' the next big thing",
  "Falling for the 'crypto will end corruption' scam",
  "Buying into every new 'art' blockchain",
  "Investing in a coin because of its 'innovative' tokenomics",
  "Getting into crypto to fund your 'escape plan'",
  "Betting on crypto because of 'insider' knowledge",
  "Buying tokens because they're 'the future of real estate'",
  "Using your kids' college fund for crypto gambling",
  "Investing in tokens with 'revolutionary' scalability",
  'Getting rekt by a sudden change in mining rewards',
  "Trading crypto because you 'see' the patterns",
  "Falling for the 'crypto will unite the world' narrative",
  "Buying into every new 'film' blockchain",
  "Investing in a coin because of its 'unique' community",
  "Getting into crypto to live the 'digital nomad' life",
  "Betting on crypto because of 'expert' charts",
  "Buying tokens because they're 'the future of education'",
  'Using your last dollar for crypto investments',
];
